#!/usr/bin/env bash
# Script: 0-change_your_home_IP
# Description: Change the IP address for localhost and facebook.com

# Make a backup of the hosts file
sudo cp /etc/hosts /etc/hosts.bak

# Modify the hosts file to change the IP addresses
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i 's/^\([0-9]\+\.\)\{3\}[0-9]\+ facebook.com/8.8.8.8 facebook.com/g' /etc/hosts

# Clear the DNS cache
sudo systemctl restart systemd-resolved.service

# Display a success message
echo "IP addresses changed successfully."

